### ISSUE TITLE
Maybe a mistake in the tutorial

### ISSUE THREAD

**Issue by Mayrixon** [pflenker/hecto-tutorial#2]
Hello, I found the behaviour of this part, which is already referenced following, is not identical to the previous version.
https://github.com/pflenker/hecto-tutorial/blob/8dede4133489af08fb37095fb6471533a15e72f5/src/main.rs#L14-L27

I am using `Rust 1.48.0` and `termion 1.5.5`.

**Comment by Mayrixon** [comment]
I tried to create a PR but failed because of the tag rather than a branch. The desired file could be found with tag `use-termion-keys`, and the whole fixed `main()` function is listed here.
```rust
fn main() {
    let _stdout = stdout().into_raw_mode().unwrap();

    for key in io::stdin().keys() {
        match key {
            Ok(key) => match key {
                Key::Char(c) => {
                    println!("{:?} ({})\r", c as u8, c);
                }
                Key::Ctrl(c) => {
                    if c != 'q' {
                        println!("{:?}\r", c as u8);
                    } else {
                        break;
                    }
                }
                _ => println!("{:?}\r", key),
            },
            Err(err) => die(err),
        }
    }
}
```

**Comment by pflenker** [comment]
Hi, thanks for opening this issue! What is the difference in behaviour you are seeing between the previous version and the new?

**Comment by Mayrixon** [comment]
Sorry I didn't test carefully. I just found my version won't work as expected. I'm writing to explain what the mistakes are and the reason these mistakes happen.

Here is a table of all behaviours.

| Input | Expected | First version | Second version |
|---|---|---|---|
|<kbd>A</kbd>|`97 (a)`|`97 (a)`|`97 (a)`|
|<kbd>Ctrl+A</kbd>|`1`|`Ctrl('a')`|`97`|

In the first version, the `match key` would not catch any ctrl-combination as we expected, says `println!("{:?}\r", c as u8);` in the branch `Key::Char(c)`. Because of the missing of a branch `Key::Ctrl(c)`, the program will execute the default branch, i.e. `println!("{:?}\r", key)`, where `key` is a `Key` not `u8`. As a result, a combination of <kbd>Ctrl+A</kbd> would be printed as `Ctrl('a')` not `1`.

In the second version, I added a match branch to deal with ctrl-combinations. However, the character `c` in `Key::Ctrl(c)` has been changed from the original input. It's not the raw input flow anymore, so the value was changed too (from `1` to `97`).

I think this issue could be fixed easily but the implementation would be ugly (for example we can use `c as u8 & 0b1111`). In this step of the tutorial, we are aiming at wrapping input flow into `Termion::Event::Key`. However, the expected result requires an expostulation on these part again.
