### ISSUE TITLE
Old terminal state isn't restored on RawTerminal drop

### ISSUE THREAD

**Issue by vruss** [pflenker/hecto-tutorial#4]
As stated on the documentation of [RawTermional](https://docs.rs/termion/1.5.3/termion/raw/struct.RawTerminal.html)

> A terminal restorer, which keeps the previous state of the terminal, and restores it, when dropped.
> Restoring will entirely bring back the old TTY state.

However, after exiting a file, the previous TTY state is not restored. I suspect, however I don't really know, that the culprit is the use of `println!` instead of writing to the `Terminal` `stdout` variable?

**Comment by pflenker** [comment]
For the sake of keeping the tutorial as close to its inspiration, `kilo`, I did not use too much of `termion`, other than setting the terminal itself into raw mode, so I never bothered to check for side effects. A PR would be welcome though :)
