### ISSUE TITLE
49 open clippy warnings at end of Chapter 6

### ISSUE THREAD

**Issue by laiudm** [pflenker/hecto-tutorial#5]
The tutorial indicates that all clippy warnings have been suppressed.

However with the latest clippy version  - clippy 0.0.212 (e1884a8 2020-12-29) - 49 warnings are emitted with the code as of end Chapter 6 - https://github.com/pflenker/hecto-tutorial/tree/navigate-left

**Comment by pflenker** [comment]
I just updated cargo to `1.49.0` and only see one warning due to a double semicolon (which was fixed in https://github.com/pflenker/hecto-tutorial/pull/1 , but not yet in the tags). I see this on linux. Can you tell me more about the environment you are running this in?

**Comment by laiudm** [comment]
Tests were on Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-132-generic x86_64).

I included the double semicolon fixes and re-ran. Partial output is below.

Any hints on what could be wrong would be appreciated.

Output:

PC:~/hecto2/hecto$ cargo --version
cargo 1.49.0 (d00d64df9 2020-12-05)
PC:~/hecto2/hecto$ cargo clippy --version
clippy 0.0.212 (e1884a8 2020-12-29)
PC:~/hecto2/hecto$ cargo clean
PC:~/hecto2/hecto$ cargo clippy
   Compiling libc v0.2.82
    Checking numtoa v0.1.0
    Checking unicode-segmentation v1.7.1
    Checking termion v1.5.5
    Checking hecto v0.1.0 (/home/d/hecto2/hecto)
warning: using a potentially dangerous silent `as` conversion
   --> src/editor.rs:208:21
    |
208 |         let width = self.terminal.size().width as usize;
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> src/main.rs:1:40
    |
1   | #![warn(clippy::all, clippy::pedantic, clippy::restriction)]
    |                                        ^^^^^^^^^^^^^^^^^^^
    = note: `#[warn(clippy::as_conversions)]` implied by `#[warn(clippy::restriction)]`
    = help: consider using a safe wrapper for this conversion
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#as_conversions

warning: using a potentially dangerous silent `as` conversion
   --> src/editor.rs:209:22
    |
209 |         let height = self.terminal.size().height as usize;
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider using a safe wrapper for this conversion
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#as_conversions

warning: using a potentially dangerous silent `as` conversion
   --> src/editor.rs:223:31
    |
223 |         let terminal_height = self.terminal.size().height as usize;
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider using a safe wrapper for this conversion
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#as_conversions

warning: using a potentially dangerous silent `as` conversion
   --> src/editor.rs:289:21
    |
289 |         let width = self.terminal.size().width as usize;
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider using a safe wrapper for this conversion
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#as_conversions

warning: using a potentially dangerous silent `as` conversion
   --> src/editor.rs:299:21
    |
299 |         let width = self.terminal.size().width as usize;
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider using a safe wrapper for this conversion
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#as_conversions

warning: using a potentially dangerous silent `as` conversion
   --> src/editor.rs:312:51
    |
312 |                 .row(self.offset.y.saturating_add(terminal_row as usize))
    |                                                   ^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider using a safe wrapper for this conversion
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#as_conversions

--- snip ---

**Comment by pflenker** [comment]
Is this on your own repository, or did you clone this one and run it direclty in the repo folder?
