### ISSUE TITLE
An Unexpected Behavior of `highlight_match`(chapter7).

### ISSUE THREAD

**Issue by 2222-42** [pflenker/hecto-tutorial#6]
In your tutorial, I found an unexpected behavior in [Chapter 7](https://www.philippflenker.com/hecto-chapter-7/)(from the section "Improve code quality").
That is, when the query matches at multi times in the same line(e.g., query is "test" and the row is "test1 and test2"), the second matched strings is not highlighted.(cf: [my test code](https://github.com/2222-42/hecto-tutorial/blob/3ec46a25edb254c6c5525582348bbb39ed45e91e/src/row.rs#L470))

The cause of this is derived from the specification of `find` of `row.rs` which returns not the index from `at` but the index from beginning of the line.
This seems easy to be fixed.

Would you mind if I send a PR to fix this?

**Comment by pflenker** [comment]
Not at all, I would appreciate the help!

**Comment by 2222-42** [comment]
Hi pflenker.
Thanks for your response.

I made a PR #7

**Comment by pflenker** [comment]
Thanks!
