### ISSUE TITLE
Consider using crossterm instead of termion

### ISSUE THREAD

**Issue by tobiasvl** [pflenker/hecto-tutorial#8]
The tutorial currently uses `termion`, which is not cross platform. There is even a warning that the tutorial doesn't work on Windows. However, [`crossterm`](https://crates.io/crates/crossterm) is cross platform and would perhaps be a good choice for a tutorial?

Of course this would require adapting the tutorial, so it's a pretty big task.

**Comment by pflenker** [comment]
Thanks for pointing it out! I unfortunately don't have the time to update/rewrite the tutorial, but at least I am now pointing out the alternative in the text.
