### ISSUE TITLE
Typo in chapter 3

### ISSUE THREAD

**Issue by mirao** [pflenker/hecto-tutorial#9]
https://www.philippflenker.com/hecto-chapter-3/
> With that change, we where able to get rid of manually checking if  has been pressed, as all keys are now properly handled for us. 

Correct is "we **were** able", isn't it?

**Comment by pflenker** [comment]
Yes, thank you! It seems that I am quite fond of making this error, I found a few other occurences of the same as well. Fixed, thank you!
